# Numpy Assignment

In [2]:
import numpy as np
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

## Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

- Yes, the variable 'list_' and 'array_list_' are different.

In [3]:
print("The datatype of variable list_ is", type(list_))
print("The datatype of array_list is", type(array_list))

The datatype of variable list_ is <class 'list'>
The datatype of array_list is <class 'numpy.ndarray'>


## Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [4]:
print("The datatype inside variable list_")
for i in list_:
    print("\tThe datatype is",type(i))

print("The datatype inside array_list")
for i in array_list:
    print("\tThe datatype is",type(i))

The datatype inside variable list_
	The datatype is <class 'str'>
	The datatype is <class 'str'>
	The datatype is <class 'str'>
	The datatype is <class 'str'>
	The datatype is <class 'str'>
The datatype inside array_list
	The datatype is <class 'numpy.str_'>
	The datatype is <class 'numpy.str_'>
	The datatype is <class 'numpy.str_'>
	The datatype is <class 'numpy.str_'>
	The datatype is <class 'numpy.str_'>


## Q3.  Considering the following changes in the variable, array_list:
####
#### array_list = np.array(object = list_, dtype = int)
####
#### Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

In [5]:
array_list = np.array(object=list_, dtype=int)

print("The datatype inside variable list_")
for i in list_:
    print("\tThe datatype is",type(i))

print("The datatype inside array_list")
for i in array_list:
    print("\tThe datatype is",type(i))

The datatype inside variable list_
	The datatype is <class 'str'>
	The datatype is <class 'str'>
	The datatype is <class 'str'>
	The datatype is <class 'str'>
	The datatype is <class 'str'>
The datatype inside array_list
	The datatype is <class 'numpy.int64'>
	The datatype is <class 'numpy.int64'>
	The datatype is <class 'numpy.int64'>
	The datatype is <class 'numpy.int64'>
	The datatype is <class 'numpy.int64'>


- Yes, the datatype for the elements inside the arrya_list have changed.

In [7]:
import numpy as np
num_list = [[1, 2, 3], [4, 5, 6]]
num_array =np.array(object=num_list)

In [8]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

## Q4. Write a code to find the following characteristics of variable, num_array:
#### (i) shape
#### (ii) size

In [9]:
np.shape(num_array)

(2, 3)

In [10]:
np.size(num_array)

6

## Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function. [Hint: The size of the array will be 9 and the shape will be (3,3).]

In [13]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Q6. Create an identity matrix of shape (5,5) using numpy functions? [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [16]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])